### PR TITLE
feat: github action - build and test

### PR DESCRIPTION
**Pull request by demo-exe**

### CODE REVIEW

**Comment by alt-romes** [comment]
Thanks!
How do you figure we can check that the tests ran successfully?

**Comment by demo-exe** [comment]
I believe you (repo owner) have to setup branch protection
Take a look at par 7 in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by demo-exe** [comment]
Also give me a second, I need to modify the test script to exit 1

**Comment by demo-exe** [comment]
fail example https://github.com/demo-exe/programmer-calculator/pull/2

Other workflows to consider:
- checking linting (whitespace etc)
- commit message (my choice: https://www.conventionalcommits.org/en/v1.0.0/)
- automagic push to aur (on demand)

**Comment by DevManu-de** [comment]
> I believe you (repo owner) have to setup branch protection Take a look at par 7 in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

I think a branch protection is a good idea and in the same run you @alt-romes could think about an approve process for pull requests in general.

**Comment by demo-exe** [comment]
@alt-romes this should be ready to merge

**Comment by alt-romes** [comment]
I've protected the master branch.

Thanks for doing this. Looks great.

> checking linting (whitespace etc)
I'd rather not do this. As mentioned elsewhere, keeping a low-barrier for entry is still one of my goals, and I don't think enforcing this would benefit us imensely -- on the contrary, it would increase friction to accepting PR and require more back-and-forth edits.

*   commit message (my choice: https://www.conventionalcommits.org/en/v1.0.0/)
> Same as above, it's a nice to have if you want to do it, but I don't want to impose it on contributors. I don't think the scope of this project warrants it.

*   automagic push to aur (on demand)
> A great idea. This is actually one of the goals in #80 

Thanks again!

**Pull request merged**
