### PR TITLE
History features #12

### PR DESCRIPTION
**Pull request by DevManu-de**
Hello,
I managed to implement following things.

- No duplicates that come after one another
- Infinite history size
- Scrolling through the stack from the top

Can you guys please test it for bugs.

Thanks.

DevManu-de

### CODE REVIEW

**Comment by alt-romes** [comment]
Nice!

I'm going to review and test it from your fork, and merge into master if I can't find problems.

Thank you,
~romes

**Comment by alt-romes** [comment]
Hello,

The reverse history scrolling is really buggy, however, it is a good idea. I was trying to fix it fast but couldn't, so it would be nice if you could fix it first.
A lot of things are buggy about it, for example: Adding just 1 number and scrolling up shows nothing, and if I add two, only the first shows or something similar. It's buggy.

You should note that before the main program loop, we are adding an `empty string` to the history, we were using this so we could revert to "empty string" when scrolling back down.

Also, I'm not sure, but I don't think we should reallocate the memory space + 1 for history every time we add something to it.
I think it would be better to have a fixed value like "20" and, if the size would ever exceed 20, we reallocate the memory to something like 20*2.

Let me know if you need help with the reverse history, tomorrow.
~romes

**Comment by DevManu-de** [comment]
Hi,

can you please describe all the bugs in history scrolling.

For the scrolling I think we had a small misunderstanding. I think to get it working the way you want it just remove the `-1` in main.c line 337. But this is not tested just an assumption.

For the realloc thing I will change that later this day.

Thanks for the feedback.

DevManu-de

**Comment by alt-romes** [comment]
Hey,
I've fixed the history scrolling bugs and added the feature: when you scroll down past the history size, the input will be set to the empty string, instead of being stuck in one of the histories.

I merged your pull request to a new `history` branch, and I'm going to apply the fix commit on top of it.

When you fix the realloc you can issue a new pull request.
If you want I can also fix it.

Thank you :),
~romes

**Pull request merged**
