### PR TITLE
Colored output #63

### PR DESCRIPTION
**Pull request by DevManu-de**
This includes a new flag `-n` that can disable colors if needed. Colors are enabled by default.

2 new functions:
- wprintw_colors()
- mvwprintw_colors()

### CODE REVIEW

**Comment by alt-romes** [comment]
Hello @DevManu-de, I'm sorry it took me so long to get back to you.
This looks good!
First off, the colours are overall good - however, I would suggest "Number or operator" to be white, and "Operation" above to be the same yellow as the operations.

Secondly, and more importantly, `./pcalc -c`, used to run tests, crashes on your fork - this needs to be fixed.

Lastly, it might be good to maintain the legacy "black & white" mode.

I could merge this onto a new branch where we can fix it, but it can probably be fixed in just one or two commits. Let me know what you think.

Additionally, we need to add a screenshot with the new colours when its done :)

**Comment by DevManu-de** [comment]
Hey @alt-romes 
i ran the tests but they complete successfully on my machine. Command used `make && ./run-tests.sh`
I can changed the colors.

Yes I agree we should keep a well maintained black&white version because not everything maybe has colors.

**Comment by alt-romes** [comment]
Okay!

I'm going to merge this onto a new branch where we can finish the "legacy-colors" (a flag should suffice) and where I can fix the segmentation fault I get on my machine.

I think the colours are better and I'll try some small variations on my own

Thank you again,
~romes

PS: (I'll look into this soon)
```
$ make && ./run-tests.sh
gcc -Wall -Wextra -g -Werror=missing-declarations -Werror=redundant-decls -Iinclude -c src/draw.c -o src/draw.o
gcc -Wall -Wextra -g -Werror=missing-declarations -Werror=redundant-decls -Iinclude -o pcalc src/draw.o src/history.o src/main.o src/numberstack.o src/operators.o src/parser.o src/xmalloc.o -lncurses #
Executing all complete!
./run-tests.sh: line 4:  2452 Done                    cat tests/$t.test
      2453 Segmentation fault: 11  | ./pcalc -c
1,7d0
< Decimal: 0, Hex: 0x0, Operation:
< Decimal: 1, Hex: 0x1, Operation:
< Decimal: 1, Hex: 0x1, Operation:
< Decimal: 1, Hex: 0x1, Operation:
< Decimal: 12, Hex: 0xc, Operation:
< Decimal: 18, Hex: 0x12, Operation:
< Decimal: 2, Hex: 0x2, Operation:
Test failed:
tests/number-bases
```

**Comment by alt-romes** [comment]
I'm sorry, I didn't notice you had already added the "legacy colours" feature!

I'm fixing my segmentation fault and after some color changes I'll ask you to check them, and then I'll merge onto master

We also need to explain this briefly in the README

Thank you kindly,
~romes

**Pull request merged**
