### PR TITLE
Fixed overflowing input

### LINKED ISSUE #52: Input window overflows
If the terminal isn't wide enough the input can overflow the input window, and the bit that ended up outside isn't removed. 
I think the solution for this would be to check if the input window is big enough for the text and otherwise to add another line to the bottom, but I'd also imagine that it would be handy if #45 is done first, so that the code for checking the window size is already there.
overflow
overflow

### PR DESCRIPTION
**Pull request by kippenjongen**
Fixed #52

### CODE REVIEW

**Comment by DevManu-de** [comment]
Hey,

I have found a problem with the fix.

The new max input is only set once after the start of pcalc.
If I resize the terminal after pcalc was started the problem still occurs.

To solve this problem you can move the 
```
    int x;
    getmaxyx(inputwin, x, x);    // Get the width of the window, slightly abusing how getmaxyx works to not have to use a second variable for the y value (which we don't need)

    int max_in = MAX_IN;
    if (x < (MAX_IN + 24)) {                      // 24 is the width that is used regardless of input, so MAX_IN + 24 is the minimum width of the terminal for MAX_IN characters of input 
        max_in = MAX_IN - ((MAX_IN + 24) - x);    // So this gives the maximum input size for a given terminal width (MAX_IN minus the difference between the minimum width for MAX_IN and the current width)
    }
```

into the input `for` loop from `get_input` and so it will be recalculated every time you enter a character.

**Comment by kippenjongen** [comment]
Thanks, its fixed now! It still isn't completely good since if the input is already longer than what it can be when the terminal is resized it still overflows, but I can't see a good way to fix that to be honest.

**Comment by alt-romes** [comment]
Hello both of you.

Thank you for your contributions!

@kippenjongen I'm going to merge #54 instead, since it's a bit cleaner

Still, thank you :)

**Comment by kippenjongen** [comment]
I agree, @DevManu-de's solution is a lot neater.

**Pull request closed without merging**
