### PR TITLE
Remove redundant declarations allowing gcc to compile

### PR DESCRIPTION
**Pull request by Mango0x45**

### CODE REVIEW

**Comment by alt-romes** [comment]
Hello,

I forgot that just because my gcc compiles without warnings it doesn't mean everyone else's does.
Is it completely unable to compile? I released the version last night kind of hurried because of the bug in change bits.
Should I release a new version for it to be able to compile ?

Thank you.

**Comment by kippenjongen** [comment]
1.7 is completely unable to compile for me at least, so I think it would be handy to make a new release.

**Comment by alt-romes** [comment]
I'm going to guess it does because of `-Werror`... my compiler completely ignored that.

Oh well, I'm releasing a patch version.

Thank you

**Comment by alt-romes** [comment]
It's done,

Let me know if your GCC is unable to compile again.

Thank you for your help

**Comment by kippenjongen** [comment]
This works!
It still gives me this warning, but it compiles and as far as I can tell runs alright, so I don't think its really a problem.

`src/operators.c: In function ‘shr’:`
`src/operators.c:99:40: warning: left shift of negative value [-Wshift-negative-value]`
`   99 |     return (b >> a) & ~((long long) -1 << (64-a));`

**Pull request merged**
