### PR TITLE
Added comments and some minor refactoring

### PR DESCRIPTION
**Pull request by kippenjongen**
This should be a bit easier to read now, let me know if there's anything else that isn't completely clear yet

### CODE REVIEW

**Comment by kippenjongen** [comment]
Sorry, this is would merge into the wrong branch

**Comment by kippenjongen** [comment]
Sorry, I'm not very good with github and knowing what does and doesn't work, this should be good now

**Comment by Mango0x45** [comment]
On the topic of refactoring, it might be beneficial to have some sort of predefined code style for this project, because at the moment the style is all over the place

**Comment by kippenjongen** [comment]
Yes, I've tried to keep my bit vaguely consistent but it didn't really work, at least partly because there wasn't really one style to begin with. Would this be something to add to #36 perhaps?

**Comment by alt-romes** [comment]
Alright, I understood the code now!

I think the problem @kippenjongen mentioned about adding "_" to the history (and actually also processing the input with "_") will be fixed by using the ncurses cursor.

@Mango0x45 there are some things that could be streamlined...but I'm unsure of how to do it. What would you suggest?

**Comment by Mango0x45** [comment]
> @Mango0x45 there are some things that could be streamlined...but I'm unsure of how to do it. What would you suggest?

Does not need to be too complicated, but I guess you could even just have a file in the repo or something that goes over how you should indent, break braces, etc. because at the moment there is code that looks like this:
```c
if (condition)
{
        /* Code */
}

switch (c) {
    case 'x':
        /* Code */
}```
and also code that looks like this:
```c
if (condition) {
        /* Code */
}

switch (c) {
case 'x':
    /* Code */
}```

**Pull request merged**
