### PR TITLE
History add_to_history() and add_number_to_history()

### PR DESCRIPTION
**Pull request by DevManu-de**
Hello,

this pr inlo covers the two mentioned improvements from #36.
For the `browsehistory()` I want to await @alt-romes comment on #38.

I didnt wait for @alt-romes comment because I wanted to reduce the merge conflicts.

If things are unclear dont hesitate to give feedback.

DevManu-de

### CODE REVIEW

**Review by alt-romes — COMMENTED** [review]
besides this, I think it's good. I'll just need to resolve the merge conflicts

**Comment by DevManu-de** [comment]
@alt-romes,

I have submitted an idea of how I think the merge conflict could be resolved.

If things are unclear why I did something please leave a comment.

**Comment by DevManu-de** [comment]
> The merge is good, I just need to point this out - I think since xrealloc will call exit_pcalc, we no longer need to error check resize_numberstack because it'll exit on it's own.

Yes this was mt intention when I made the `xfunctions`


For the `exit_pcalc` I thought that it would be useful to have a more detailed output for every exit code.
my plan is and it is on my fork (https://github.com/DevManu-de/programmer-calculator/blob/history/src/main.c):
```
switch (code) {

        case 0: break;
        case -1: fprintf(stderr, "OUT OF MEMORY\n"); break;

}
```

Later I thought we add more error codes to give more information on what went wrong.
I just think that my approach is easy to understand and to modify.
Maybe we can `#define MEM_FAIL -1` (and other failures) to make changes later to the values and to make the code more readable.

**Comment by alt-romes** [comment]
It's done. I've applied the changes I mentioned and added your suggestion to add `MEM_FAIL`

Thank you for your help 👍

**Pull request merged**
