### PR TITLE
Adds support for left and right arrow keys

### PR DESCRIPTION
**Pull request by kippenjongen**
A fix for #33. Its not very well done probably, and it would probably be a lot neater and would actually use the curses cursor instead of an underscore to mark where you are typing if it used curses more, but this will probably do for the time.

### CODE REVIEW

**Comment by alt-romes** [comment]
Okay so I was trying to review your code:

1) You could add some comments to help clear the code up and help contributors understand it

2) It's working well! But as you said, it needs some work as it would be nice to use the ncurses cursor.

I'm going to merge this into a new branch - let's try to use the ncurses cursor (if possible) before closing this issue

Thank you so much 👍 
~romes

**Comment by kippenjongen** [comment]
Ok, I'll add some more comments, sorry for not doing that before. I'll also have a look at using the ncurses cursor, I didn't do that before because I'm not really familiar with ncurses and I thought it would be better to have at least something first, but I will do that now too.

**Comment by alt-romes** [comment]
There's no problem!
If you commit the comments first, I might be able to help with ncurses as well.

Short ncurses introduction:

In our program we use 2 ncurses `WINDOW`. The `displaywin` and the `inputwin`

You'll be probably working just with the `inputwin`.

There's a function called `move` which takes 2 parameters `(int y, int x)` and moves the cursor.
There's a function called `wmove` which takes 3 parameters `(WINDOW, int y, int x)` to move the cursor in the window <- we'll probably want to use this one

Thank you 💪 
~romes

**Comment by kippenjongen** [comment]
Yep, I'm working on the comments now! Thanks for the intro, I did have a quick look and found `wmove` but I couldn't get it to work that quickly, as I think it was already being called in some other places which messed things up a bit, but once I'm done with the comments we can have another look!

**Pull request merged**
